rules:
  - name: Helper functions
    script: ./rules/helper_functions.js
    stage: login_success
    enabled: true
    order: 1
  - name: Prompt user to verify or create their account
    script: ./rules/prompt_verify_or_create_account.js
    stage: login_success
    enabled: true
    order: 2
  - name: Prompt user to add a verified phone number
    script: ./rules/prompt_add_verified_phone_number.js
    stage: login_success
    enabled: false
    order: 3
  - name: Link identities to primary user
    script: ./rules/link_identities_to_primary_user.js
    stage: login_success
    enabled: true
    order: 4
rulesConfigs:
  - key: RULES_CLIENT_ID
    value: '##RULES_CLIENT_ID##'
  - key: RULES_CLIENT_SECRET
    value: '##RULES_CLIENT_SECRET##'
  - key: PROMPT_APP_BASE_URL
    value: '##PROMPT_APP_BASE_URL##'
hooks: []
pages:
  - name: login
    enabled: true
    html: ./pages/login.html
resourceServers:
  - name: Demo API
    identifier: 'urn:demo-api'
    allow_offline_access: false
    signing_alg: RS256
    skip_consent_for_verifiable_first_party_clients: true
    token_lifetime: 86400
    token_lifetime_for_web: 7200
clients:
  - name: API Explorer Application
    app_type: non_interactive
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      rotation_type: non-rotating
      expiration_type: non-expiring
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
  - name: Prompt
    allowed_clients: []
    allowed_logout_urls:
      - 'https://api-demo-prompt.demo/'
      - 'https://auth0-api-demo-prompt.example.com/'
    app_type: regular_web
    callbacks:
      - 'https://api-demo-prompt.demo/callback'
      - 'https://auth0-api-demo-prompt.example.com/callback'
    client_aliases: []
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - implicit
      - client_credentials
      - 'http://auth0.com/oauth/grant-type/passwordless/otp'
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    logo_uri: >-
      https://example.com/logo.jpg
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
  - name: Rules
    app_type: non_interactive
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
  - name: Test App Demo
    allowed_clients: []
    allowed_logout_urls:
      - 'api.demo.TestApp://api-demo.us.auth0.com/ios/api.demo.TestApp/callback'
    app_type: native
    callbacks:
      - 'api.demo.TestApp://example.us.auth0.com/ios/api.demo.TestApp/callback'
      - 'api2.demo.TestApp://example.us.auth0.com/ios/api2.demo.TestApp/callback'
    client_aliases: []
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - implicit
      - refresh_token
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    logo_uri: >-
      https://example.com/app_logo.jpg
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: none
  - name: Test App
    allowed_clients: []
    allowed_logout_urls:
      - 'https://api-demo.us.webtask.run/auth0-authentication-api-debugger'
    app_type: regular_web
    callbacks:
      - 'https://api-demo.us.webtask.run/auth0-authentication-api-debugger'
    client_aliases: []
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - implicit
      - refresh_token
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
  - name: auth0-deploy-cli
    app_type: non_interactive
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
databases:
  - name: api-customers
    strategy: auth0
    enabled_clients:
      - auth0-deploy-cli
      - Prompt
      - Test App
      - Test App Demo
      - API Explorer Application
    is_domain_connection: false
    options:
      mfa:
        active: true
        return_enroll_settings: true
      import_mode: false
      disable_signup: false
      passwordPolicy: null
      password_history:
        size: 5
        enable: false
      strategy_version: 2
      requires_username: false
      password_dictionary:
        enable: false
        dictionary: []
      brute_force_protection: true
      password_no_personal_info:
        enable: false
      password_complexity_options:
        min_length: 1
      enabledDatabaseCustomization: false
    realms:
      - api-customers
connections:
  - name: email
    strategy: email
    enabled_clients:
      - Prompt
    is_domain_connection: false
    options:
      name: email
      totp:
        length: 6
        time_step: 180
      email:
        body: ./email.html
        from: '{{ application.name }} <root@auth0.com>'
        syntax: liquid
        subject: 'Welcome to {{ application.name }}'
      disable_signup: false
      brute_force_protection: true
  - name: sms
    strategy: sms
    enabled_clients:
      - Prompt
      - Test App
      - Test App Demo
    is_domain_connection: false
    options:
      from: '##TWILIO_SMS_FROM_PHONE##'
      name: sms
      totp:
        length: 6
        time_step: 180
      syntax: md_with_macros
      template: 'Your verification code is: @@password@@'
      twilio_sid: '##TWILIO_SID##'
      twilio_token: '##TWILIO_TOKEN##'
      disable_signup: false
      messaging_service_sid: null
      brute_force_protection: true
  - name: google-oauth2
    strategy: google-oauth2
    enabled_clients:
      - Prompt
      - Test App
      - Test App Demo
    is_domain_connection: false
    options:
      client_id: '##GOOGLE_CLIENT_ID##'
      client_secret: '##GOOGLE_CLIENT_SECRET##'
      email: true
      scope:
        - email
        - profile
      profile: true
tenant:
  enabled_locales:
    - en
  flags:
    allow_legacy_delegation_grant_types: false
    allow_legacy_ro_grant_types: false
    allow_other_legacy_grant_types: false
    new_universal_login_experience_enabled: true
    universal_login: true
    disable_clickjack_protection_headers: false
  friendly_name: Test App
  picture_url: >-
      https://example.com/logo.jpg
  support_email: ''
  support_url: ''
  universal_login:
    colors:
      page_background: '#FFFFFF'
      primary: '#0D2769'
emailProvider:
  name: smtp
  credentials:
    smtp_host: smtp.mailtrap.io
    smtp_port: 2525
    smtp_user: '##SMTP_PROVIDER_USERNAME##'
    smtp_pass: '##SMTP_PROVIDER_PASSWORD##'
  default_from_address: Test App <noreply@example.com>
  enabled: true
emailTemplates: []
clientGrants:
  - client_id: API Explorer Application
    audience: 'https://api-demo.us.auth0.com/api/v2/'
    scope:
      - 'read:client_grants'
      - 'create:client_grants'
      - 'delete:client_grants'
      - 'update:client_grants'
      - 'read:users'
      - 'update:users'
      - 'delete:users'
      - 'create:users'
      - 'read:users_app_metadata'
      - 'update:users_app_metadata'
      - 'delete:users_app_metadata'
      - 'create:users_app_metadata'
      - 'read:user_custom_blocks'
      - 'create:user_custom_blocks'
      - 'delete:user_custom_blocks'
      - 'create:user_tickets'
      - 'read:clients'
      - 'update:clients'
      - 'delete:clients'
      - 'create:clients'
      - 'read:client_keys'
      - 'update:client_keys'
      - 'delete:client_keys'
      - 'create:client_keys'
      - 'read:connections'
      - 'update:connections'
      - 'delete:connections'
      - 'create:connections'
      - 'read:resource_servers'
      - 'update:resource_servers'
      - 'delete:resource_servers'
      - 'create:resource_servers'
      - 'read:device_credentials'
      - 'update:device_credentials'
      - 'delete:device_credentials'
      - 'create:device_credentials'
      - 'read:rules'
      - 'update:rules'
      - 'delete:rules'
      - 'create:rules'
      - 'read:rules_configs'
      - 'update:rules_configs'
      - 'delete:rules_configs'
      - 'read:hooks'
      - 'update:hooks'
      - 'delete:hooks'
      - 'create:hooks'
      - 'read:actions'
      - 'update:actions'
      - 'delete:actions'
      - 'create:actions'
      - 'read:email_provider'
      - 'update:email_provider'
      - 'delete:email_provider'
      - 'create:email_provider'
      - 'blacklist:tokens'
      - 'read:stats'
      - 'read:tenant_settings'
      - 'update:tenant_settings'
      - 'read:logs'
      - 'read:logs_users'
      - 'read:shields'
      - 'create:shields'
      - 'update:shields'
      - 'delete:shields'
      - 'read:anomaly_blocks'
      - 'delete:anomaly_blocks'
      - 'update:triggers'
      - 'read:triggers'
      - 'read:grants'
      - 'delete:grants'
      - 'read:guardian_factors'
      - 'update:guardian_factors'
      - 'read:guardian_enrollments'
      - 'delete:guardian_enrollments'
      - 'create:guardian_enrollment_tickets'
      - 'read:user_idp_tokens'
      - 'create:passwords_checking_job'
      - 'delete:passwords_checking_job'
      - 'read:custom_domains'
      - 'delete:custom_domains'
      - 'create:custom_domains'
      - 'update:custom_domains'
      - 'read:email_templates'
      - 'create:email_templates'
      - 'update:email_templates'
      - 'read:mfa_policies'
      - 'update:mfa_policies'
      - 'read:roles'
      - 'create:roles'
      - 'delete:roles'
      - 'update:roles'
      - 'read:prompts'
      - 'update:prompts'
      - 'read:branding'
      - 'update:branding'
      - 'delete:branding'
      - 'read:log_streams'
      - 'create:log_streams'
      - 'delete:log_streams'
      - 'update:log_streams'
      - 'create:signing_keys'
      - 'read:signing_keys'
      - 'update:signing_keys'
      - 'read:limits'
      - 'update:limits'
      - 'create:role_members'
      - 'read:role_members'
      - 'delete:role_members'
  - client_id: Prompt
    audience: 'https://api-demo.us.auth0.com/api/v2/'
    scope:
      - 'read:users'
      - 'update:users'
      - 'create:users'
      - 'read:tenant_settings'
  - client_id: Rules
    audience: 'https://api-demo.us.auth0.com/api/v2/'
    scope:
      - 'read:users'
      - 'update:users'
guardianFactors:
  - name: duo
    enabled: false
  - name: email
    enabled: false
  - name: otp
    enabled: false
  - name: push-notification
    enabled: false
  - name: sms
    enabled: false
guardianFactorProviders: []
guardianFactorTemplates: []
guardianPolicies:
  policies: []
guardianPhoneFactorSelectedProvider:
  provider: auth0
guardianPhoneFactorMessageTypes:
  message_types: []
roles: []
branding:
  colors:
    page_background: '#FFFFFF'
    primary: '#0D2769'
  logo_url: >-
      https://example.com/logo.jpg
prompts:
  universal_login_experience: new
migrations: {}